//! Portable v1 contracts for AI-agent-friendly file normalization.

#![deny(private_bounds, private_interfaces, unreachable_pub)]

mod error;
mod io;
mod model;
mod registry;
mod schema;

pub use error::NormalizerError;
pub use error::NormalizerErrorCategory;
pub use error::NormalizerErrorCode;
pub use error::NormalizerFuture;
pub use error::NormalizerResult;
pub use io::ArtifactSink;
pub use io::ArtifactWriter;
pub use io::BytesInputSource;
pub use io::Cancellation;
pub use io::InputSource;
pub use io::MaterializedInput;
pub use io::MemoryArtifactSink;
pub use io::NeverCancelled;
pub use io::NoProgress;
pub use io::NoScratchSpace;
pub use io::NormalizationContext;
pub use io::NormalizationRequest;
pub use io::ProbeRequest;
pub use io::ProgressReporter;
pub use io::ScratchSpace;
pub use io::finish_text_normalization;
pub use io::read_all;
pub use io::write_locator_map;
pub use io::write_primary_text;
pub use model::AgentFileProfile;
pub use model::ArtifactRole;
pub use model::ArtifactSpecification;
pub use model::FormatId;
pub use model::InputMatcher;
pub use model::InputMetadata;
pub use model::NORMALIZER_PROTOCOL_VERSION;
pub use model::NormalizationDiagnostic;
pub use model::NormalizationDiagnosticLevel;
pub use model::NormalizationProgress;
pub use model::NormalizationReport;
pub use model::NormalizationStatistics;
pub use model::NormalizedFormat;
pub use model::NormalizedMapping;
pub use model::NormalizerCapabilities;
pub use model::NormalizerConfig;
pub use model::NormalizerDescriptor;
pub use model::NormalizerIdentity;
pub use model::OriginalLocator;
pub use model::ProbeResult;
pub use model::ProducedArtifact;
pub use model::ProgressPhase;
pub use model::ResourceLimits;
pub use model::RetrievalProfile;
pub use model::ToolSupport;
pub use model::ToolSupportLevel;
pub use model::WorkEstimate;
pub use model::WorkUnit;
pub use registry::ConfiguredNormalizer;
pub use registry::Normalizer;
pub use registry::NormalizerFactory;
pub use registry::NormalizerRegistry;
pub use registry::default_probe;
pub use registry::empty_config;
pub use registry::empty_config_schema;
pub use registry::validate_empty_config;
pub use schema::schema_document;
