[package]
name = "context-config"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
agent-file-normalizer = { workspace = true }
agent-source-connector = { workspace = true }
context-structure = { workspace = true }
globset = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
context-structure-parser-markdown = { workspace = true }
context-structure-parser-tree-sitter-typescript = { workspace = true }
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
